/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;
import tienda.Cliente;
import tienda.Main;

/**
 *
 * @author Carla Daniela
 */
public class Interfaz extends javax.swing.JFrame {
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        boton = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        campoid_user = new javax.swing.JTextField();
        camponombre = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        jlabeln = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton.setBackground(new java.awt.Color(255, 51, 51));
        boton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        boton.setForeground(new java.awt.Color(255, 255, 255));
        boton.setText("SALIR");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 90, 40));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, 280));

        id.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        id.setText("ID: ");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 40, -1));

        campoid_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoid_userActionPerformed(evt);
            }
        });
        getContentPane().add(campoid_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 220, 30));

        camponombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponombreActionPerformed(evt);
            }
        });
        getContentPane().add(camponombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 220, 30));

        entrar.setBackground(new java.awt.Color(51, 153, 0));
        entrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setText("ENTRAR");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 120, 30));

        jlabeln.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlabeln.setText("NOMBRE:");
        getContentPane().add(jlabeln, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondito.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonActionPerformed

    private void camponombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponombreActionPerformed

    }//GEN-LAST:event_camponombreActionPerformed
    
    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        String nombreIngresado = camponombre.getText();
        String idIngresado = campoid_user.getText();

        boolean encontrado = false;
        for (Cliente cliente : Main.listaClientes) {
            if (cliente.getNombre().equals(nombreIngresado) && cliente.getIdCliente().equals(idIngresado)) {
                encontrado = true;
                break;
            }
        }

        if (encontrado) {
            new SegundaVentana().setVisible(true);
            this.dispose();  // Cierra la ventana de login
        } else {
            JOptionPane.showMessageDialog(this, "Nombre o ID incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_entrarActionPerformed

    private void campoid_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoid_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoid_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JTextField campoid_user;
    private javax.swing.JTextField camponombre;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel id;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jlabeln;
    // End of variables declaration//GEN-END:variables
}
